# Generated by Django 3.0.8 on 2020-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8000)),
                ('url', models.CharField(max_length=8000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
